export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  const backgroundStyle = 
  {
    backgroundColor: '#0072f0' // KEEP - OFFICIAL BLUE ATB COLOUR
  }

  return (
    <html style={backgroundStyle} lang="en">
      <body>{children}</body>
    </html>
  )
}
