import { UserProvider } from '@auth0/nextjs-auth0/client';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  const backgroundStyle =
  {
    backgroundColor: '#0072f0' // KEEP - OFFICIAL BLUE ATB COLOUR
  }

  return (
    <html style={backgroundStyle} lang="en">
      <UserProvider>
          <body>{children}</body>
      </UserProvider>
    </html>
  )
}
